server.port=8095

spring.application.name=SVACHAM_MANAGEMENT

spring.data.mongodb.uri=mongodb+srv://ravikiranreddy7567_db_user:ravi1234@svacham.nd1upch.mongodb.net/svacham?retryWrites=true&w=majority&appName=svacham

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true